server:
  port: 9993

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5421/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: admin
      username: root
      password: example
      port: 27777
      host: localhost
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        device-events-history-input-stream:
          group: group-history
          destination: device_events
          contentType: application/json
        device-status-history-input-stream:
          group: group-historyy
          destination: device_status
          contentType: application/json

#logging:
#  level:
#    com.iot.device_status: DEBUG
