server:
  port: 9992

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5421/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      database: admin
      username: root
      password: example
      port: 27777
      host: localhost
  cloud:
    stream:
      defaultBinder : kafka
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            brokers: localhost:9092
      bindings:
        base-device-events-stream-input:
          group: group-2
          destination: device_events
          contentType: application/json
        device-status-stream-output:
          destination: device_status
          contentType: application/json
