server:
  port: 9990

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5421/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          base-device-events-stream:
            destination: base_device_events
            contentType: application/json
